# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'disign.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_Lee(object):
    def setupUi(self, Lee):
        Lee.setObjectName("Lee")
        Lee.resize(639, 330)
        Lee.setMinimumSize(QtCore.QSize(639, 330))
        Lee.setMaximumSize(QtCore.QSize(639, 330))
        self.centralwidget = QtWidgets.QWidget(Lee)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 311, 221))
        self.groupBox.setObjectName("groupBox")
        self.LenLabel = QtWidgets.QLabel(self.groupBox)
        self.LenLabel.setGeometry(QtCore.QRect(10, 30, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LenLabel.setFont(font)
        self.LenLabel.setObjectName("LenLabel")
        self.len = QtWidgets.QLineEdit(self.groupBox)
        self.len.setGeometry(QtCore.QRect(160, 30, 41, 20))
        self.len.setObjectName("len")
        self.StartLabel = QtWidgets.QLabel(self.groupBox)
        self.StartLabel.setGeometry(QtCore.QRect(10, 60, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.StartLabel.setFont(font)
        self.StartLabel.setObjectName("StartLabel")
        self.start = QtWidgets.QLineEdit(self.groupBox)
        self.start.setGeometry(QtCore.QRect(160, 60, 41, 20))
        self.start.setObjectName("start")
        self.FinLabel = QtWidgets.QLabel(self.groupBox)
        self.FinLabel.setGeometry(QtCore.QRect(10, 90, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.FinLabel.setFont(font)
        self.FinLabel.setObjectName("FinLabel")
        self.finish = QtWidgets.QLineEdit(self.groupBox)
        self.finish.setGeometry(QtCore.QRect(160, 90, 41, 20))
        self.finish.setObjectName("finish")
        self.BarierLabel = QtWidgets.QLabel(self.groupBox)
        self.BarierLabel.setGeometry(QtCore.QRect(10, 130, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.BarierLabel.setFont(font)
        self.BarierLabel.setObjectName("BarierLabel")
        self.barriers = QtWidgets.QLineEdit(self.groupBox)
        self.barriers.setGeometry(QtCore.QRect(10, 150, 291, 21))
        self.barriers.setObjectName("barriers")
        self.build = QtWidgets.QPushButton(self.groupBox)
        self.build.setGeometry(QtCore.QRect(10, 180, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.build.setFont(font)
        self.build.setObjectName("build")
        self.field = QtWidgets.QTextEdit(self.centralwidget)
        self.field.setGeometry(QtCore.QRect(345, 30, 281, 211))
        self.field.setObjectName("field")
        self.WayLabel = QtWidgets.QLabel(self.centralwidget)
        self.WayLabel.setGeometry(QtCore.QRect(10, 260, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.WayLabel.setFont(font)
        self.WayLabel.setObjectName("WayLabel")
        self.Way = QtWidgets.QTextEdit(self.centralwidget)
        self.Way.setGeometry(QtCore.QRect(60, 260, 571, 23))
        self.Way.setObjectName("Way")
        Lee.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Lee)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 639, 21))
        self.menubar.setObjectName("menubar")
        self.file = QtWidgets.QMenu(self.menubar)
        self.file.setObjectName("file")
        self.Info = QtWidgets.QMenu(self.menubar)
        self.Info.setObjectName("Info")
        Lee.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Lee)
        self.statusbar.setObjectName("statusbar")
        Lee.setStatusBar(self.statusbar)
        self.About = QtWidgets.QAction(Lee)
        self.About.setObjectName("About")
        self.open_file = QtWidgets.QAction(Lee)
        self.open_file.setObjectName("open_file")
        self.save_file = QtWidgets.QAction(Lee)
        self.save_file.setObjectName("save_file")
        self.file.addAction(self.open_file)
        self.file.addAction(self.save_file)
        self.Info.addAction(self.About)
        self.menubar.addAction(self.file.menuAction())
        self.menubar.addAction(self.Info.menuAction())

        self.retranslateUi(Lee)
        QtCore.QMetaObject.connectSlotsByName(Lee)

        scriptDir = os.path.dirname(os.path.realpath(__file__))
        self.setWindowIcon(QtGui.QIcon(scriptDir + os.path.sep + 'icon/icon.ico'))

    def retranslateUi(self, Lee):
        _translate = QtCore.QCoreApplication.translate
        Lee.setWindowTitle(_translate("Lee", "Lee alghoritm"))
        self.groupBox.setTitle(_translate("Lee", "Данные"))
        self.LenLabel.setText(_translate("Lee", "Длинна лабиринта"))
        self.StartLabel.setText(_translate("Lee", "Стартовая позиция"))
        self.FinLabel.setText(_translate("Lee", "Финишная позция"))
        self.BarierLabel.setText(_translate("Lee", "Барьеры"))
        self.build.setText(_translate("Lee", "Создать лабиринт"))
        self.WayLabel.setText(_translate("Lee", "Путь"))
        self.file.setTitle(_translate("Lee", "Файл"))
        self.Info.setTitle(_translate("Lee", "Справка"))
        self.About.setText(_translate("Lee", "О программе"))
        self.open_file.setText(_translate("Lee", "Открыть"))
        self.save_file.setText(_translate("Lee", "Сохранить"))